// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title TableChainBooking
 * @dev Decentralized restaurant table booking fee escrow & payment verification.
 * Built for TableChain (Ethereum Sepolia Testnet).
 */
contract TableChainBooking {
    address public owner;
    uint256 public platformFeePercent = 5; // 5% platform protocol fee

    enum PaymentStatus { None, Paid, Refunded, Settled }

    struct Booking {
        string bookingId;
        address customer;
        address payable restaurantWallet;
        uint256 amount;
        uint256 timestamp;
        PaymentStatus status;
        bool exists;
    }

    // Mapping from unique bookingId (e.g. TC-20261010-00125) to Booking record
    mapping(string => Booking) public bookings;
    
    // Mapping from customer wallet to array of their booking IDs
    mapping(address => string[]) private customerBookings;

    // Events
    event BookingPaid(
        string indexed bookingIdIndexed,
        string bookingId,
        address indexed customerWallet,
        address indexed restaurantWallet,
        uint256 amount,
        uint256 timestamp
    );

    event BookingSettled(
        string indexed bookingId,
        address indexed restaurantWallet,
        uint256 amountToRestaurant,
        uint256 feeToPlatform
    );

    event BookingRefunded(
        string indexed bookingId,
        address indexed customerWallet,
        uint256 refundAmount
    );

    modifier onlyOwner() {
        require(msg.sender == owner, "TableChain: Caller is not owner");
        _;
    }

    constructor() {
        owner = msg.sender;
    }

    /**
     * @notice Pay the booking fee for a restaurant reservation.
     * @param bookingId The unique alphanumeric booking ID generated by TableChain backend.
     * @param restaurantWallet The verified on-chain address of the restaurant.
     */
    function payBookingFee(
        string calldata bookingId,
        address payable restaurantWallet
    ) external payable {
        require(msg.value > 0, "TableChain: Booking fee must be greater than 0");
        require(bytes(bookingId).length > 0, "TableChain: Invalid booking ID");
        require(restaurantWallet != address(0), "TableChain: Invalid restaurant wallet");
        require(!bookings[bookingId].exists, "TableChain: Booking ID already paid on-chain");

        bookings[bookingId] = Booking({
            bookingId: bookingId,
            customer: msg.sender,
            restaurantWallet: restaurantWallet,
            amount: msg.value,
            timestamp: block.timestamp,
            status: PaymentStatus.Paid,
            exists: true
        });

        customerBookings[msg.sender].push(bookingId);

        emit BookingPaid(
            bookingId,
            bookingId,
            msg.sender,
            restaurantWallet,
            msg.value,
            block.timestamp
        );
    }

    /**
     * @notice Simplified payBookingFee with pre-configured or default restaurant mapping.
     */
    function payBookingFeeDirect(string calldata bookingId) external payable {
        require(msg.value > 0, "TableChain: Booking fee must be greater than 0");
        require(bytes(bookingId).length > 0, "TableChain: Invalid booking ID");
        require(!bookings[bookingId].exists, "TableChain: Booking ID already paid on-chain");

        bookings[bookingId] = Booking({
            bookingId: bookingId,
            customer: msg.sender,
            restaurantWallet: payable(owner),
            amount: msg.value,
            timestamp: block.timestamp,
            status: PaymentStatus.Paid,
            exists: true
        });

        customerBookings[msg.sender].push(bookingId);

        emit BookingPaid(
            bookingId,
            bookingId,
            msg.sender,
            owner,
            msg.value,
            block.timestamp
        );
    }

    /**
     * @notice Verify payment status of a booking ID on-chain.
     */
    function getBooking(string calldata bookingId) external view returns (
        string memory _bookingId,
        address customer,
        address restaurantWallet,
        uint256 amount,
        uint256 timestamp,
        PaymentStatus status
    ) {
        require(bookings[bookingId].exists, "TableChain: Booking does not exist");
        Booking memory b = bookings[bookingId];
        return (
            b.bookingId,
            b.customer,
            b.restaurantWallet,
            b.amount,
            b.timestamp,
            b.status
        );
    }

    /**
     * @notice Settle booking fee to the restaurant upon successful dining completion.
     */
    function settleBooking(string calldata bookingId) external onlyOwner {
        Booking storage b = bookings[bookingId];
        require(b.exists, "TableChain: Booking does not exist");
        require(b.status == PaymentStatus.Paid, "TableChain: Invalid payment status for settlement");

        b.status = PaymentStatus.Settled;
        uint256 platformFee = (b.amount * platformFeePercent) / 100;
        uint256 restaurantAmount = b.amount - platformFee;

        (bool sentRestaurant, ) = b.restaurantWallet.call{value: restaurantAmount}("");
        require(sentRestaurant, "TableChain: Failed to transfer to restaurant");

        emit BookingSettled(bookingId, b.restaurantWallet, restaurantAmount, platformFee);
    }

    /**
     * @notice Refund booking fee back to customer (e.g. valid cancellation policy).
     */
    function refundBooking(string calldata bookingId) external onlyOwner {
        Booking storage b = bookings[bookingId];
        require(b.exists, "TableChain: Booking does not exist");
        require(b.status == PaymentStatus.Paid, "TableChain: Invalid payment status for refund");

        b.status = PaymentStatus.Refunded;
        (bool sentCustomer, ) = payable(b.customer).call{value: b.amount}("");
        require(sentCustomer, "TableChain: Failed to refund customer");

        emit BookingRefunded(bookingId, b.customer, b.amount);
    }

    /**
     * @notice Get all booking IDs associated with a customer address.
     */
    function getCustomerBookings(address customer) external view returns (string[] memory) {
        return customerBookings[customer];
    }

    receive() external payable {}
}
